[providers]
python = "3.11"
nodejs = "18"

[phases.install]
cmds = [
    'pip install -r requirements.txt',
    'cd cv-builder-frontend && npm ci'
]

[phases.build]
cmds = ['cd cv-builder-frontend && npm run build']

[start]
cmd = 'cd cv-builder-backend && uvicorn main:app --host 0.0.0.0 --port $PORT'